language: node_js
sudo: false
git:
  depth: 1
cache:
  yarn: true
matrix:
  include:
    - node_js: "12"
      script: npm run jest -- --runInBand
      env: CI=tests 12
    - node_js: "10"
      script: npm run jest -- --runInBand --coverage
      env: CI=coverage
    - node_js: "10"
      script: npm run pretest
      env: CI=pretest

before_install:
  - npm install -g npm@latest
